### ISSUE TITLE
AttributeError: 'StdLogger' object has no attribute 'isatty'

### ISSUE THREAD

**Issue by DomHudson** [comet-ml/comet-quickstart-guide#7]
## Summary
Hi,
I'm getting a traceback raised during training of a Keras' model. This only happenes with an instantiated comet.Experiment class at the top of the file.

If you need any more information, please let me know!
Many thanks,
Dom

## Environment
```
comet-ml (0.1.40)
Python 3.5.2 (default, Sep 14 2017, 22:51:06) 

Distributor ID:    Ubuntu
Description:   Ubuntu 16.04.3 LTS
Release:      16.04
Codename: xenial
```

## Traceback
```
Traceback (most recent call last):
  File "run_polarity2.py", line 481, in <module>
    model.fit(X_train, y_train, epochs = 2, validation_data = (X_test, y_test))
  File "/home/dom/env/lib/python3.5/site-packages/keras/models.py", line 893, in fit
    initial_epoch=initial_epoch)
  File "/home/dom/env/lib/python3.5/site-packages/comet_ml/keras_logger.py", line 15, in wrapper
    return real_fit(*args, **kwargs)
  File "/home/dom/env/lib/python3.5/site-packages/keras/engine/training.py", line 1631, in fit
    validation_steps=validation_steps)
  File "/home/dom/env/lib/python3.5/site-packages/keras/engine/training.py", line 1161, in _fit_loop
    callbacks.on_epoch_begin(epoch)
  File "/home/dom/env/lib/python3.5/site-packages/keras/callbacks.py", line 59, in on_epoch_begin
    callback.on_epoch_begin(epoch, logs)
  File "/home/dom/env/lib/python3.5/site-packages/keras/callbacks.py", line 276, in on_epoch_begin
    verbose=self.verbose)
  File "/home/dom/env/lib/python3.5/site-packages/keras/utils/generic_utils.py", line 270, in __init__
    self._dynamic_display = (sys.stdout.isatty() or
AttributeError: 'StdLogger' object has no attribute 'isatty'
uploading stats to Comet before program termination (may take several seconds)
go to https://www.comet.ml/view/jLVzb*****************to view your run.
```

## Model
```
model = Sequential()
model.add(Embedding(output_dim = 300, input_dim = 10000, mask_zero = True))        
model.add(Bidirectional(LSTM(32, dropout = 0.2, activation = 'tanh')))
model.add(Dense(1, activation = 'sigmoid'))

model.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)

model.fit(X_train, y_train, epochs = 2, validation_data = (X_test, y_test))
```

**Comment by gidim** [comment]
Working on a fix. What Keras version are you using?

**Comment by DomHudson** [comment]
Thanks a lot Gideon!

```
Keras (2.0.9)
tensorflow (1.4.0)
tensorflow-tensorboard (0.4.0rc2)
```

**Comment by DomHudson** [comment]
Nope it was running in a screen (program) session

**Comment by gidim** [comment]
Just pushed a fix. Can you let me know if it solved it?
Make sure you upgrade our library:
`pip install comet_ml --upgrade`

**Comment by DomHudson** [comment]
Fantastic! It has fixed it yes. It's caused the Keras' verbose=1 progress bar to print one line per bar update though but that's relatively minor. Many thanks for such a quick turnaround!

**Comment by gidim** [comment]
Yes. We're aware of that.  This way we're reducing the number of lines we need to send to the server. Hopefully you'll get better indication of your training using the chart in the UI?

**Comment by DomHudson** [comment]
Yep chart is much better - thanks!
